src/Entity/Article.php
<?php

namespace App\Entity;

use App\Entity\Traits\Timestampable;
use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class Article
{
    use Timestampable;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id_article;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\Length(min = 3)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min = 10)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $alias;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    public function getId(): ?int
    {
        return $this->id_article;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }



    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

templates/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BlogController!{% endblock %}

{% block body %}
	<h1>{{article.titre|capitalize}}</h1>
	<div>{{article.description|capitalize}}</div>
	<div>publié le <i>{{article.getDatePublication()|date('d/m/Y')}}</i></div>
	<p class="pl-3 pb-3 text-muted">
		<small>
			créé par {{ article.userId.firstName }} {{ article.userId.lastName }}
		</small>
	</p>
	{% if article.getUserId() == app.user %}
		<a href="{{ path('app_edit',{id:article.id}) }}" class="btn btl-light">Edition</a>|
		<a href="#" onclick="confirm('Vous êtes sur ?') && document.getElementById('delete-article').submit();" class="btn btl-light">Supprimer</a>|
	{% endif %}
	<a href="{{ path('blog') }}" class="btn btl-light">Retour</a>
	<form id="delete-article" action="{{ path('app_delete',{id:article.id}) }}" method="post" style="display:none;">
		<input type="hidden" name="csrf_token" value="{{ csrf_token('delete_article'~article.id) }}">
		<input type="hidden" name="_method" value="DELETE">
	</form>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}{% endblock %}
</head>
<body>
{% include 'menu.html.twig'%}
<div class="container">
    <div class="row">
        <div class="col">
            {% block body %}{% endblock %}
{#            {% block javascripts %}{% endblock %}#}
        </div>
    </div>
</div>
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

templates/menu.html.twig
{% block menu %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ path("blog") }}">My Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if app.user %}
                        <li class="nav-item">
                            <a class="nav-link " href="{{ path('app_create') }}" aria-disabled="true">Créer un article</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{{ path('app_mes_articles') }}" aria-disabled="true">Mes articles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{{ path('app_logout') }}" tabindex="-1">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link active" href="{{ path('app_register') }}" tabindex="-1">S'inscrire</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{{ path('app_login') }}" tabindex="-1">Login</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        {%  if app.user %}
                            <a class="nav-link btn btn-secondary" >{{ app.user.firstName }}</a>
                        {% else %}
                            <a class="nav-link btn btn-secondary" href="{{ path('app_login') }}" >non connecté</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}